# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
julie = User.create!(email:"patujulie@gmail.com", password: "julie", username: "patujulie")
martin = User.create!(email:"hoetmartin@gmail.com", password: "martin", username: "hoetmartin")
louis = User.create!(email:"mggtlouism@gmail.com", password: "louis", username: "louismggt")
pierre = User.create!(email:"ledankpierre@gmail.com", password: "pierre", username: "ledank")
martind = User.create!(email:"martinderr@gmail.com", password: "martin", username: "martinderr")
antoine = User.create!(email:"toniomass@gmail.com", password: "antoine", username: "toniomass")
mika = User.create!(email:"mikadu62@gmail.com", password: "mika", username: "mikadu62")
remi = User.create!(email:"remsansfa@gmail.com", password: "remi", username: "remisansfafa")
olivier = User.create!(email:"olivmat@gmail.com", password: "olivier", username: "lifiertakclabatri")
valentin = User.create!(email:"vavalemaire@gmail.com", password: "valentin", username: "valleroux")

nain_de_merde = Statue.create!(user: julie , category: "petite sculpture", surface: 15, description:  "entrée de gamme", price: 5, photo: "https://cdn.mycrazystuff.com/15836/nain-de-jardin-i-m-sexy-an-i-gnome-it.jpg")
lalique = Statue.create!(user: martin, category: "petite sculpture", surface: 40, description:  "haut de gamme ", price: 45, photo: "https://cdn.mycrazystuff.com/15836/nain-de-jardin-i-m-sexy-an-i-gnome-it.jpg")
aphrodite = Statue.create!(user: louis, category: "petite sculpture", surface: 50, description:  "milieu de gamme ", price: 20, photo: "https://cdn.mycrazystuff.com/15836/nain-de-jardin-i-m-sexy-an-i-gnome-it.jpg")
visage_grec = Statue.create!(user: pierre, category: "moyenne sculpture", surface: 70, description:  "entrée de gamme ", price: 10, photo: "https://cdn.mycrazystuff.com/15836/nain-de-jardin-i-m-sexy-an-i-gnome-it.jpg")
le_cavalier = Statue.create!(user: martind, category: "moyenne sculpture", surface: 77, description:  "milieu de gamme ", price: 40, photo: "https://cdn.mycrazystuff.com/15836/nain-de-jardin-i-m-sexy-an-i-gnome-it.jpg")
leclair = Statue.create!(user: antoine, category: "moyenne sculpture", surface: 90, description:  "entrée de gamme ", price:  25, photo: "https://cdn.mycrazystuff.com/15836/nain-de-jardin-i-m-sexy-an-i-gnome-it.jpg")
zig_zag = Statue.create!(user: mika, category: "moyenne sculpture", surface: 100, description: "haut de gamme ", price: 100, photo: "https://cdn.mycrazystuff.com/15836/nain-de-jardin-i-m-sexy-an-i-gnome-it.jpg")
amazone = Statue.create!(user: remi, category: "grande sculpture", surface: 150, description: "milieu de gamme ", price: 90, photo: "https://cdn.mycrazystuff.com/15836/nain-de-jardin-i-m-sexy-an-i-gnome-it.jpg")
sculpture_de_julie = Statue.create!(user: olivier, category: "grande sculpture", surface: 164, description: "entrée de gamme ", price: 1, photo: "https://cdn.mycrazystuff.com/15836/nain-de-jardin-i-m-sexy-an-i-gnome-it.jpg")
tour_eiffel = Statue.create!(user: valentin, category: "grande sculpture", surface: 250 , description: "haut de gamme ", price: 200, photo: "https://cdn.mycrazystuff.com/15836/nain-de-jardin-i-m-sexy-an-i-gnome-it.jpg")

Review.create!(content:"Amazing product, recommend", stars: 4, user: julie, statue: nain_de_merde)
Review.create!(content:"Good product!", stars: 3, user: martin, statue: lalique)
Review.create!(content:"Sculpture of quality", stars: 3, user: louis, statue: aphrodite)
Review.create!(content:"The sculpture worked perfectly in my exhibition", stars: 4, user: pierre, statue: visage_grec)
Review.create!(content:"Thanks for this work of art at an affordable price", stars: 5, user: martind, statue: le_cavalier)
Review.create!(content:"perfect for decorating your parade ", stars: 4, user: olivier, statue: leclair)
Review.create!(content:"Recommended.", stars: 3, user: valentin, statue: zig_zag)
Review.create!(content:"Super produit, je recommende", stars: 4, user: antoine, statue: sculpture_de_julie)
Review.create!(content:"calidad de mierda", stars: 2, user: mika, statue: amazone)
Review.create!(content:"fragile sculpture", stars: 1, user: remi, statue: tour_eiffel)

Rental.create!(description: "Private party", start_date: Date.new(2019,10,18), end_date: Date.new(2019,10,20), user: antoine, statue: nain_de_merde)
Rental.create!(description: "fashion show", start_date: Date.new(2019,11,12), end_date: Date.new(2019,11,15), user: julie, statue: nain_de_merde)
Rental.create!(description: "Private party", start_date: Date.new(2019,12,22), end_date: Date.new(2019,01,01), user: martin, statue: nain_de_merde)
Rental.create!(description: "Birthday", start_date: Date.new(2020,01,04), end_date: Date.new(2020,01,05), user: louis, statue: nain_de_merde)
Rental.create!(description: "Showroom", start_date: Date.new(2020,06,10), end_date: Date.new(2020,06,12), user: martind, statue: nain_de_merde)
Rental.create!(description: "Birthday", start_date: Date.new(2020,07,17), end_date: Date.new(2020,07,19), user: mika, statue: nain_de_merde)
Rental.create!(description: "Showroom", start_date: Date.new(2020,04,10), end_date: Date.new(2020,04,30), user: remi, statue: nain_de_merde)
Rental.create!(description: "Private party", start_date: Date.new(2020,09,14), end_date: Date.new(2020,09,17), user: valentin, statue: nain_de_merde)
Rental.create!(description: "Showroom", start_date: Date.new(2020,04,23), end_date: Date.new(2020,04,26), user: pierre, statue: nain_de_merde)
Rental.create!(description: "Christmas event", start_date: Date.new(2019,12,01), end_date: Date.new(2020,01,01), user: olivier, statue: nain_de_merde)
